/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Oddoreven;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ajinv
 */
public class Oddevenframe extends javax.swing.JFrame {

    /**
     * Creates new form Oddevenframe
     */
    static int count=0;
    static int score=0;
    Random r = new Random();
    int randnumber;
    public Oddevenframe() {
        initComponents();
        randnumber=r.nextInt(100);
        numberlabel.setText(String.valueOf(randnumber));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Oddbutton = new javax.swing.JButton();
        Evenbutton = new javax.swing.JButton();
        numberlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Yourscore = new javax.swing.JLabel();
        Gamename = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Oddbutton.setBackground(new java.awt.Color(255, 51, 0));
        Oddbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Oddbutton.setText("ODD");
        Oddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OddbuttonActionPerformed(evt);
            }
        });

        Evenbutton.setBackground(new java.awt.Color(0, 102, 255));
        Evenbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Evenbutton.setText("EVEN");
        Evenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvenbuttonActionPerformed(evt);
            }
        });

        numberlabel.setText("0");

        jLabel2.setText("SCORE :");

        Yourscore.setText("0");

        Gamename.setText("ODDorEVEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(numberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Oddbutton)
                        .addGap(41, 41, 41)
                        .addComponent(Evenbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Yourscore, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gamename, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Gamename)
                .addGap(50, 50, 50)
                .addComponent(numberlabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oddbutton)
                    .addComponent(Evenbutton))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Yourscore))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OddbuttonActionPerformed
        // TODO add your handling code here:
        count=count+1;
        int number=Integer.parseInt(numberlabel.getText());
        if(count==10)
        {
            if(number%2!=0){
                score=score+1;
                Yourscore.setText(String.valueOf(score));
                randnumber=r.nextInt(100);
                numberlabel.setText(String.valueOf(randnumber));
                           }
            JOptionPane.showMessageDialog(this,"Your score : "+score+"/10");
            count=0;
            score=0;
            Yourscore.setText(String.valueOf(score));
        }
        else
        {
            if(number%2!=0){
                score=score+1;
                Yourscore.setText(String.valueOf(score));
                randnumber=r.nextInt(100);
                numberlabel.setText(String.valueOf(randnumber));
        }
            else{
               randnumber=r.nextInt(100);
               numberlabel.setText(String.valueOf(randnumber));
            }
        }
        
    }//GEN-LAST:event_OddbuttonActionPerformed

    private void EvenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvenbuttonActionPerformed
        // TODO add your handling code here:
        count=count+1;
        int number=Integer.parseInt(numberlabel.getText());
        if(count==10){
            if(number%2==0){
                score=score+1;
                Yourscore.setText(String.valueOf(score));
                randnumber=r.nextInt(100);
                numberlabel.setText(String.valueOf(randnumber));
                
                           }
            JOptionPane.showMessageDialog(this,"Your score : "+score+"/10");
            count=0;
            score=0;
            Yourscore.setText(String.valueOf(score));
        }
        else{
            if(number%2==0){
                score=score+1;
                Yourscore.setText(String.valueOf(score));
                randnumber=r.nextInt(100);
                numberlabel.setText(String.valueOf(randnumber));
                
        }
            else{
                randnumber=r.nextInt(100);
                numberlabel.setText(String.valueOf(randnumber));
            }
        }
    }//GEN-LAST:event_EvenbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oddevenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oddevenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oddevenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oddevenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oddevenframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Evenbutton;
    private javax.swing.JLabel Gamename;
    private javax.swing.JButton Oddbutton;
    private javax.swing.JLabel Yourscore;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel numberlabel;
    // End of variables declaration//GEN-END:variables
}
